server:
 port: 8082
 context-path: /ui
 session:
    cookie: UISESSION


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: clientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
       userInfoUri : http://localhost:8081/auth/rest/hello

spring:
  thymeleaf:
    cache: false
